DROP DATABASE mciprojetos;
CREATE DATABASE mciprojetos;

USE mciprojetos;



CREATE TABLE clientes(
clienteid INT NOT NULL AUTO_INCREMENT, 
nomecliente VARCHAR(60) NOT NULL,
logradouro VARCHAR(50) NOT NULL,
cnpj VARCHAR(14) NOT NULL,
pais VARCHAR(15) NOT NULL,  
cidade VARCHAR(50) NOT NULL,
bairro VARCHAR(50) NOT NULL,
estado VARCHAR(50) NOT NULL,
uf VARCHAR(2) NOT NULL,
cep VARCHAR(8) NOT NULL,
telefone VARCHAR(15) NOT NULL,
celular VARCHAR(15),
email VARCHAR(30),
datacadastro VARCHAR(20),
statuscliente BOOLEAN NOT NULL,
PRIMARY KEY (clienteid, cnpj));

CREATE TABLE clientmapping(
mappingid INT NOT NULL AUTO_INCREMENT,
nomecliente VARCHAR(60) NOT NULL,
businessmanager VARCHAR(60) NOT NULL,
accountmanager VARCHAR(60) NOT NULL,
creator VARCHAR(60) NOT NULL,
questao1 FLOAT (10,2) NOT NULL, -- 1) Qual o potencial de budget para ativações e eventos no ano?
questao2 INT NOT NULL, -- 2) Quantos solicitantes de eventos há na empresa?
questao3 VARCHAR(100) NOT NULL, -- 3) Quem são os maiores solicitantes (mais verba destinada à eventos)? (nome/cargo/e-mail/telefone)maiorcompr VARCHAR(50) NOT NULL,
questao4 VARCHAR(100) NOT NULL, -- 4) Quem é o maior comprador?
questao5 VARCHAR(100) NOT NULL, -- 5) Todos os BIDs passam por Compras? Descreva o processo de solicitações. Há uma área de Eventos na empresa? O Departamento de Compras se envolve? A solicitação vem direto do marketing/trade?
questao6 VARCHAR(100) NOT NULL, -- 6) Quais departamentos solicitam eventos? Que tipo de eventos casa um deles realiza?
questao7 VARCHAR(20) NOT NULL, -- 7) O processo é  job a job via homologação? (verificar contrato vigente)
questao8 VARCHAR(40) NOT NULL, -- 8) Se homologação, há contrato? Quando será feita a próxima homologação?
questao9 FLOAT(10,2), -- 9) Quanto comprou da MCI em 2017 / 2018?
questao10 VARCHAR(60) NOT NULL, -- 10) Quais são as agencias que estao dentro do cliente? (quem são nossos concorrentes?)
questao11 VARCHAR(60) NOT NULL, -- 11) Vocês homologam empresa de Cenografia e AV? Se sim, quando será feita a próxima homologação?
PRIMARY KEY (mappingid, nomecliente));
	



CREATE TABLE usuarios(
userid INT NOT NULL AUTO_INCREMENT,
nomecomp VARCHAR(60) NOT NULL,
bl VARCHAR(30) NOT NULL,
email VARCHAR(60) NOT NULL,
password VARCHAR(15) NOT NULL,
PRIMARY KEY (userid, email));

INSERT INTO usuarios (nomecomp, bl, email, password) values ('paulo henrique bezerra', 'HUB', 'paulo.bezerra@mci-group.com','123');

CREATE TABLE projetos(
projectid INT NOT NULL AUTO_INCREMENT,
clienteid VARCHAR(60) NOT NULL,
area VARCHAR(20) NOT NULL,
cidade VARCHAR(50) NOT NULL,
uf VARCHAR(2) NOT NULL,
owner VARCHAR(30) NOT NULL,
propreqdate VARCHAR(20) NOT NULL,
mcistdcliname VARCHAR (30) NOT NULL,
projectname VARCHAR (80) NOT NULL,
projectanalcode INT NOT NULL,
eventstartdate VARCHAR(20) NOT NULL,
eventstatus VARCHAR (10) NOT NULL, -- past, present, future
eventclosingdate VARCHAR(20) NOT NULL,
paxnumber INT NOT NULL,
cancelinsurance VARCHAR (30), -- verificar
probability INT NOT NULL,
projectstatus VARCHAR (10) NOT NULL, -- open, lost, won
projectaudit VARCHAR (10) NOT NULL, -- EM PROD, AUDITADO, REALIZADO
turnoverforowner FLOAT (10,2) NOT NULL,
gmforowner FLOAT (10,2) NOT NULL,
gmturnoverperc INT, -- percentage
weightedprospec FLOAT (10,2) NOT NULL,
userid INT NOT NULL,
datacadastro VARCHAR(20) NOT NULL,
FOREIGN KEY (userid) REFERENCES usuarios (userid),	
PRIMARY KEY (projectid, projectname));

INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','CILAD 2018',2132,now(),'past',now(),30,'vazio',50,'Open','Auditado',100.944,33.139,50,80.474,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TNT','TNT CAMPUS PARTY',1860,now(),'Past',now(),0,'vazio',1,'Confirmed','AUDITADO',110940.81,33139,0.298708834016986,33139,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'NATULAB','CAMPANHA DE INCENTIVO 2017',1470,now(),'Past',now(),80,'vazio',1,'Confirmed','AUDITADO',0,80704,0,80704,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SYNGENTA','CONVENÇÃO L&G LATAM 2018',0,now(),'Past',now(),60,'vazio',0,'Lost','0',300000,38365,0.127883333333333,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'RCI  BANQUE','CAMPANHA DE INCENTIVO - TOP REDE 2017/18',1525,now(),'Past',now(),350,'vazio',1,'Confirmed','AUDITADO',0,163380,0,163380,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'MONGERAL','GALO DE OURO',1708,now(),'Past',now(),350,'vazio',1,'Confirmed','AUDITADO',994779.79,197398,0.198433866454002,197398,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'PFIZER CH','PCH CONVENÇÃO DE VENDAS 2018 + ATIVAÇÃO PRODUTOS ADVIL E CENTRUM',1731,now(),'Past',now(),100,'vazio',1,'Confirmed','AUDITADO',258820.32,76858.73,0.296957866368452,76858.73,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'AIG','CASA AIG - WORLD CUP 18',1813,now(),'Future',now(),0,'vazio',1,'Confirmed','PRODUCAO',515900,125000,0.242295018414421,125000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'VOLVO','CAMPANHA CLÃ VOLVO 2017/18',1537,now(),'Past',now(),107,'vazio',1,'Confirmed','0',150000,8000,0.0533333333333333,8000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','3º FORUM DE PEDIATRIA',0,now(),'Past',now(),350,'vazio',0,'Lost','0',400000,80000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','2º FORUM DE DIABETES',1873,now(),'Past',now(),400,'vazio',1,'Confirmed','0',510000,152256.86,0.298542862745098,152256.86,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ASTELLAS','CONGRESSO URO-ONCOLOGIA',0,now(),'Past',now(),0,'vazio',0,'Lost','0',70000,14000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ABBOTT / ALERE','POC DAY 2018',1858,now(),'Past',now(),70,'vazio',1,'Confirmed','EM PROD ',139000,32000,0.23021582733813,32000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ASTELLAS','ASCO - HIGHLIGHTS 2018',0,now(),'Past',now(),200,'vazio',0,'Lost','0',500000,100000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'GALDERMA','MAP 2.0 ',0,now(),'Future',now(),600,'vazio',0,'Lost','0',490000,90000,0.183673469387755,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'GALDERMA','ROADSHOW MAP',0,now(),'Past',now(),0,'vazio',0,'Lost','0',270000,52000,0.192592592592593,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'GALDERMA','LANÇAMENTO EPIDUO',0,now(),'Future',now(),300,'vazio',0,'Canceled','0',284000,57000,0.200704225352113,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'HUSQVARNA','CONVENÇÃO DE VENDAS 2018',0,now(),'Past',now(),300,'vazio',0,'Canceled','0',1300000,260000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ROYAL CARIBBEAN','LANÇAMENTO SY',0,now(),'Past',now(),120,'vazio',0,'Canceled','0',250000,45000,0.18,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SWISSCAM','8th WORLD WATER FORUM',1844,now(),'Past',now(),0,'vazio',1,'Confirmed','AUDITADO',202318.03,12172,0.0601627052220704,12172,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'VOLVO','CAMPANHA DE INCENTIVO VOLVO 2018',0,now(),'Past',now(),120,'vazio',0,'Lost','0',600000,120000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'AWMAY','GALA DINNER',1859,now(),'Past',now(),170,'vazio',1,'Confirmed','AUDITADO',318148.07,80828,0.254057803965305,80828,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'LIBERTY SEGUROS','CONVENÇÃO DE VENDAS 2018',0,now(),'Past',now(),400,'vazio',0,'Lost','0',1400000,200000,0.142857142857143,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'EDITORA ABRIL','VERÃO VEJA 2019',0,now(),'Future',now(),0,'vazio',0,'Canceled','0',800000,240000,0.3,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'PFIZER   ','LANÇAMENTO DUAVIVE',2028,now(),'Future',now(),0,'vazio',1,'Confirmed','0',900000,180000,0.2,180000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SULAMÉRICA','II FÓRUM MÉDICO SULAMERICA',0,now(),'Past',now(),450,'vazio',0,'Canceled','0',480000,48000,0.1,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'LUPIN','CONVENÇÃO 2018 E LANÇAMENTO LUPIN',0,now(),'Past',now(),300,'vazio',0,'Lost','0',400000,80000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'BIODERMA','WRVD 2018',1874,now(),'Future',now(),400,'vazio',1,'Confirmed','EM PROD',3500000,500000,0.142857142857143,500000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','EBT 2018 (ENCONTRO BRASILEIRO DE TIREÓIDE)',1917,now(),'Past',now(),0,'vazio',1,'Confirmed','AUDITADO',200325.18,61779,0.308393582873606,61779,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'EMBRAER','EEOC BRASIL',1910,now(),'Past',now(),225,'vazio',1,'Confirmed','REALIZA',380000,106110,0.279236842105263,106110,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'RCI  BANQUE','CAMPANHA DE INCENTIVO TOP RCI 2018',1872,now(),'Present',now(),200,'vazio',1,'Confirmed','EM PROD',320000,130000,0.40625,130000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','CONGRESSOS RESPIRATÓRIA 2018',0,now(),'Future',now(),0,'vazio',0,'Lost','0',590000,120000,0.203389830508475,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'YOUNG & RUBICAM','LG FANFEST',0,now(),'Future',now(),0,'vazio',0,'Canceled','0',800000,175000,0.21875,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SBC','CORAÇÕES EM MOVIMENTO',0,now(),'Future',now(),15000,'vazio',0,'Canceled','0',3000000,500000,0.166666666666667,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','17º CONGRESSO DE CIRURGIA NO JOELHO',0,now(),'Past',now(),0,'vazio',0,'Lost','0',45000,9000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','73º CONGRESSO BRASILEIRO DE CARDIOLOGIA',0,now(),'Future',now(),0,'vazio',0,'Lost','0',500000,100000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'MSD','LANÇAMENTO KEYTRUDA COMBO',1915,now(),'Future',now(),350,'vazio',1,'Confirmed','EM PROD',1300000,260000,0.2,260000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'PROBIÓTICA','ARNOLD CLASSICS',0,now(),'Past',now(),0,'vazio',0,'Canceled','0',375000,85000,0.226666666666667,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ULTRAGÁZ','CALENDARIO FESTAS NACIONAIS - 69 FILIAIS',0,now(),'Future',now(),69,'vazio',0.25,'Open','0',700000,150000,0.214285714285714,37500,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','XVI ENCONTRO DE CIRURGIA VASCULAR E ENDOVASCULAR SP',2004,now(),'Past',now(),0,'vazio',1,'Confirmed','REALIZA',64800,16781,0.258966049382716,16781,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','CONGRESSO PANAMERICANO DE CIRURGIA CARDIO-VASCULAR RJ',2005,now(),'Future',now(),0,'vazio',1,'Confirmed','REALIZA',71800,16200,0.225626740947075,16200,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','CONGRESSO CARDIOLOGIA DO ESTADO DE SÃO PAULO',2073,now(),'Past',now(),0,'vazio',1,'Confirmed','REALIZA',113000,25000,0.221238938053097,25000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','IRON ACADEMY',1900,now(),'Future',now(),250,'vazio',1,'Confirmed','REALIZA',450000,98000,0.217777777777778,98000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','CONGRESSO DAS DOENÇAS FUNCIONAIS DO APARELHO DIGESTIVO',0,now(),'Past',now(),0,'vazio',0,'Lost','0',19000,4500,0.236842105263158,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'EDITORA ABRIL','ELLE FASHION BALL',0,now(),'Future',now(),900,'vazio',0,'Lost','0',800000,160000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'RCI  BANQUE','LANÇAMENTO FAST TRACK + CAMPANHA FROTAS 2018',0,now(),'Past',now(),100,'vazio',0,'Canceled','0',120000,25000,0.208333333333333,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'RCI  BANQUE','CONVENÇÃO TREINAMENTO F&I',0,now(),'Past',now(),100,'vazio',0,'Canceled','0',130000,28000,0.215384615384615,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','CONGRESSO URGÊNCIAS E EMERGÊNCIAS PEDIÁTRICAS',2048,now(),'Past',now(),0,'vazio',1,'Confirmed','REALIZA',84683.98,23675,0.279568815731145,23675,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ABBOTT','PROJETO AÇÕES INOVADORAS - ESTAGIÁRIOS',0,now(),'Future',now(),0,'vazio',0,'Canceled','0',10000,4000,0.4,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ALATUR','PROJETO INCENTIVO RAÍZEN - VOCÊ CONQUISTA 2019',0,now(),'Future',now(),1050,'vazio',0.25,'Open','0',4000000,500000,0.125,125000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ASTELLAS','SOBRAFO',2047,now(),'Past',now(),0,'vazio',1,'Confirmed','REALIZA',35600,9492,0.266629213483146,9492,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'COCA-COLA','CAMPANHA JUNTOS SOMOS +',0,now(),'Future',now(),0,'vazio',0,'Lost','0',250000,50000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ERNEST & YOUNG','PALESTRA PRESIDENTE',0,now(),'Past',now(),150,'vazio',0,'Lost','0',90000,22000,0.244444444444444,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'MERCADO LIVRE','ATIVAÇÃO V.TEX DAY 2018',2050,now(),'Past',now(),0,'vazio',1,'Confirmed','REALIZA',110936,32000,0.288454604456624,32000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'MERCADO LIVRE','AÇÕES ML EXPERIENCE',0,now(),'Past',now(),0,'vazio',0,'Lost','0',20000,10000,0.5,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'MERZ','2th REGIONAL SALES MEETING',2063,now(),'Future',now(),303,'vazio',1,'Confirmed','0',1000000,135000,0.135,135000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'MET LIFE','ASSEMBLÉIA MULTIPREV',0,now(),'Past',now(),80,'vazio',0,'Canceled','0',50000,10000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'INSTITUTO DA LONGEVIDADE','PROJETO FEIRA 50+',0,now(),'Future',now(),0,'vazio',0.5,'Open','0',2500000,200000,0.08,100000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'MONGERAL','EXPERT 2018',0,now(),'Future',now(),0,'vazio',0,'Lost','0',280000,60000,0.214285714285714,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','CERDELGA',2049,now(),'Future',now(),100,'vazio',1,'Confirmed','0',350000,70000,0.2,70000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','CONGRESSO GAUCHO DE PEDIATRIA',2091,now(),'Past',now(),0,'vazio',1,'Confirmed','REALIZA',38065.26,14157,0.371913918360206,14157,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TV GLOBO','ENDOMARKETING TV GLOGO (SEDE)',2054,now(),'Past',now(),200,'vazio',1,'Confirmed','0',31421.19,12600.93,0.401032869856298,12600.93,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'YOUNG & RUBICAM','LOOK DO DIA BARTIRA - AÇÃO METRÔ',0,now(),'Future',now(),0,'vazio',0,'Canceled','0',150000,30000,0.2,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'YOUNG & RUBICAM','HAPPN - AÇÃO APP',0,now(),'Future',now(),0,'vazio',0,'Canceled','0',271000,55000,0.202952029520295,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ABAG','LABACE - 2018',2070,now(),'Future',now(),0,'vazio',1,'Confirmed','0',2100000,150000,0.0714285714285714,150000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'ABBOTT','CLINICAS DE VACINAS ALERE',2132,now(),'Future',now(),30,'vazio',1,'Confirmed','0',40000,15000,0.375,15000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'E&Y','SEMINÁRIO E PALESTRA PERSIDENTE E&Y',0,now(),'Past',now(),150,'vazio',0,'Lost','0',99900,25000,0.25025025025025,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TV GLOBO','ATIVAÇÃO COPA - SITES SP E RJ',0,now(),'Future',now(),0,'vazio',0.25,'LOST','0',275000,45000,0.163636363636364,11250,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','CILAD 2018',0,now(),'Future',now(),0,'vazio',0.5,'Open','0',64000,15000,0.234375,7500,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','CONGRESSO BRASILEIRO DE DERMATOLOGIA',0,now(),'Future',now(),0,'vazio',0.5,'Open','0',40000,10000,0.25,5000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI','CONGRESSO BRASILEIRO DE NEFROLOGIA',0,now(),'Future',now(),0,'vazio',0.5,'Open','0',65000,16000,0.246153846153846,8000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SANOFI MEDLEY','CONGRESSO CÉREBRO E EMOÇÕES 2018',2133,now(),'Future',now(),0,'vazio',1,'Confirmed','EM PROD',278333,52000,0.186826571049786,52000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SOUL.ME','PROJETO SOUL.ME & ALMA.VIDA',0,now(),'Future',now(),0,'vazio',0.5,'Open','0',2500000,250000,0.1,125000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TV GLOBO','BGS & CP | TV GLOBO & CLARO',0,now(),'Future',now(),0,'vazio',0.25,'Open','0',1400000,300000,0.214285714285714,75000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TV GLOBO','BGS & CP | TV GLOBO & TNT',0,now(),'Future',now(),0,'vazio',0.5,'Open','0',300000,60000,0.2,30000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','CBEM',0,now(),'Future',now(),0,'vazio',0,'Lost','0',250000,65000,0.26,0,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TV GLOBO','workshop globo',0,now(),'Future',now(),30,'vazio',0.6,'Open','0',300000,60000,0.2,36000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'COTY','CONVENÇÃO CONSUMER BEAUTY 2018',0,now(),'Future',now(),500,'vazio',0.5,'lost','0',350000,70000,0.2,35000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','2 FORUM DII',0,now(),'Future',now(),300,'vazio',0.5,'Open','0',400000,80000,0.2,40000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','SOCESP',0,now(),'Future',now(),0,'vazio',0.5,'Open','0',150000,80000,0.533333333333333,40000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TAKEDA','FIGO',0,now(),'Future',now(),0,'vazio',0.5,'Open','0',120000,80000,0.666666666666667,40000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'COB','PRÊMIO BRASIL OLÍMPICO',0,now(),'Future',now(),700,'vazio',0.5,'Open','0',850000,150000,0.176470588235294,75000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'SOMOS','LANÇAMENTO STUDIUM',0,now(),'Future',now(),1000,'vazio',0.5,'Open','0',300000,60000,0.2,30000,1,now());
INSERT INTO projetos (clienteid, area, cidade, uf, owner, propreqdate, mcistdcliname, projectname, projectanalcode, eventstartdate, eventstatus, eventclosingdate, paxnumber, cancelinsurance, probability, projectstatus, projectaudit, turnoverforowner, gmforowner, gmturnoverperc, weightedprospec, userid, datacadastro) VALUES (1,'HUB','Sao Paulo','SP','paulo.bezerra@mci-group.com',now(),'TITAN PNEUS','CONVENÇÃO',0,now(),'Future',now(),94,'vazio',0.25,'Open','0',350000,70000,0.2,17500,1,now());
